/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#341100",
        "on-tertiary-container": "#ffab7f",
        "on-secondary-container": "#626566",
        "inverse-surface": "#293040",
        "background": "#f9f9ff",
        "on-secondary-fixed-variant": "#454748",
        "surface-tint": "#4156b9",
        "secondary-container": "#e1e3e4",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#edf0ff",
        "surface-container-low": "#f1f3ff",
        "tertiary": "#5f2500",
        "tertiary-fixed": "#ffdbcb",
        "surface": "#f9f9ff",
        "surface-container-high": "#e1e8fd",
        "surface-container": "#e9edff",
        "surface-container-highest": "#dce2f7",
        "primary-container": "#2e44a7",
        "primary-fixed-dim": "#b9c3ff",
        "outline": "#757684",
        "on-primary-fixed-variant": "#263da0",
        "primary": "#0f2a90",
        "secondary-fixed-dim": "#c5c7c8",
        "surface-bright": "#f9f9ff",
        "tertiary-fixed-dim": "#ffb691",
        "on-primary-fixed": "#001258",
        "on-secondary-fixed": "#191c1d",
        "on-surface": "#141b2b",
        "tertiary-container": "#833600",
        "on-background": "#141b2b",
        "secondary": "#5c5f60",
        "on-primary-container": "#afbbff",
        "error-container": "#ffdad6",
        "primary-fixed": "#dee1ff",
        "surface-variant": "#dce2f7",
        "surface-dim": "#d3daef",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed": "#e1e3e4",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#793100",
        "inverse-primary": "#b9c3ff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c5c5d4",
        "on-surface-variant": "#454652",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin": "32px",
        "md": "1.5rem",
        "xs": "0.5rem",
        "unit": "4px",
        "lg": "2.5rem",
        "sm": "1rem",
        "xl": "4rem"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        "h1": ["Inter"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"],
        "display": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "h2": ["Inter"]
      },
      fontSize: {
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
